import amazon_logo from "../assets/amazon_logo.webp";
import crypto_logo from "../assets/crypto_logo.webp";
import traingenius_logo from "../assets/traingenius_logo.webp";

export const HERO_CONTENT_ENG = `I'm a Back-End Developer focused on Java and Spring, with experience in building scalable APIs. Currently studying Analysis and Development of Systems at the Federal Institute of São Paulo, I’m passionate about creating efficient solutions and continuously improving my skills in the tech world.`;

export const HERO_CONTENT_PT = `Sou um Desenvolvedor Back-End focado em Java e Spring, com experiência na construção de APIs escaláveis. Atualmente, cursando Análise e Desenvolvimento de Sistemas no Instituto Federal de São Paulo, sou apaixonado por criar soluções eficientes e aprimorar minhas habilidades constantemente.`;

export const ABOUT_TEXT_ENG = `I'm Luiz Felipe, a 19-year-old Back-End Developer. Currently studying Systems Analysis and Development at the Federal Institute of São Paulo. Focused on Java, Spring, and building robust backend APIs. Almost 2 years of experience in software development.`;

export const ABOUT_TEXT_PT = `Sou Luiz Felipe, desenvolvedor Back-End de 19 anos. Atualmente, cursando Análise e Desenvolvimento de Sistemas no Instituto Federal de São Paulo. Focado em Java, Spring e construção de APIs robustas. Quase 2 anos de experiência em desenvolvimento de software.`;

export const TECHNOLOGIES_TEXT_ENG = `Studying Java, Spring, and building backend APIs.`;

export const TECHNOLOGIES_TEXT_PT = `Estudando Java, Spring e desenvolvimento de APIs backend.`;

export const PROJECTS_ENG = [
  {
    title: "Amazon Scraper",
    image: amazon_logo,
    description: "A web application that extracts product data (title, image, rating, and price) from Amazon Brazil and Amazon US based on user search keywords.",
    technologies: ["Javascript", "Bun", "Puppeteer", "Express"],
    github_link: "https://github.com/luizsolely/amazon-scraper"
  },
  {
    title: "Crypto Price Tracker",
    image: crypto_logo,
    description: "A web application for real-time cryptocurrency price tracking. Academic project that fetches and displays updated data from various cryptocurrencies through a public API.",
    technologies: ["Javascript", "React", "Express", "LowDB"],
    github_link: "https://github.com/luizsolely/react-express"
  },
  {
    title: "TrainGenius API",
    image: traingenius_logo,
    description: "A RESTful API for managing workouts generated by AI and manually created. Includes secure authentication and unit tests.",
    technologies: [
      "Java",
      "SpringBoot",
      "MapStruct",
      "JUnit 5",
      "Mockito"
    ],
    github_link: "https://github.com/luizsolely/train-genius"
  }
];

export const PROJECTS_PT = [
  {
    title: "Amazon Scraper",
    image: amazon_logo,
    description: "Uma aplicação web que extrai dados de produtos (título, imagem, avaliação e preço) da Amazon Brasil e Amazon US com base em palavras-chave de busca fornecidas pelo usuário.",
    technologies: ["Bun", "Puppeteer", "Express"],
    github_link: "https://github.com/luizsolely/amazon-scraper"
  },
  {
    title: "Crypto Price Tracker",
    image: crypto_logo,
    description: "Uma aplicação web para rastreamento de preços de criptomoedas. Projeto acadêmico que busca e exibe dados atualizados de várias criptomoedas através de uma API pública.",
    technologies: ["React", "Express", "LowDB"],
    github_link: "https://github.com/luizsolely/react-express"
  },
  {
    title: "TrainGenius API",
    image: traingenius_logo,
    description: "API RESTful para gerenciamento de treinos gerados por IA e criados manualmente. Inclui autenticação JWT e testes unitários.",
    technologies: [
      "Java",
      "SpringBoot",
      "MapStruct",
      "JUnit 5",
      "Mockito"
    ],
    github_link: "https://github.com/luizsolely/train-genius"
  }
];

export const EXPERIENCES_ENG = [
  {
    year: "Mai, 2024 - Present",
    role: "IT Apprentice",
    company: "Covre Transportes",
    description: `Technical Support, handling of equipment such as installation, formatting, and updating of PCs and laptops, use of company software, network infrastructure, etc.`,
    technologies: [],
  }
];

export const EXPERIENCES_PT = [
  {
    year: "Mai, 2024 - Presente",
    role: "Aprendiz de TI",
    company: "Covre Transportes",
    description: `Suporte Técnico, manuseio de equipamentos como instalação, formatação e atualização de PCs e laptops, uso de software da empresa, infraestrutura de rede, etc.`,
    technologies: [],
  }
];

export const CONTACT_ENG = {
  address: "Rádio Clube, Santos, Brazil",
  phoneNo: "+55 13 9 9196-6900",
  email: "luizsolely@gmail.com",
};

export const CONTACT_PT = {
  address: "Rádio Clube, Santos, Brasil",
  phoneNo: "+55 13 9 9196-6900",
  email: "luizsolely@gmail.com",
};
